services:
    davidiq.topictitlecolor.listener:
        class: davidiq\topictitlecolor\event\main_listener
        arguments:
            - @auth
            - @user
            - @dbal.conn
            - @template
            - @request
            - %core.table_prefix%
        tags:
            - { name: event.listener }
